-- =========================================================
-- QUADRAID INTELLIGENT WATER TREATMENT - SUPABASE SCHEMA
-- Run this script in your Supabase SQL Editor
-- (https://supabase.com/dashboard/project/sgycillziknffxmjwgoq/sql/new)
-- =========================================================

-- 1. Create sensor_readings table
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    flow_rate_l_hr NUMERIC,
    today_production_l NUMERIC,
    tds_input NUMERIC,
    tds_output NUMERIC,
    ph NUMERIC,
    orp NUMERIC,
    turbidity NUMERIC,
    temperature NUMERIC,
    conductivity NUMERIC,
    dissolved_oxygen NUMERIC,
    free_chlorine NUMERIC,
    inlet_pressure NUMERIC,
    pump_pressure NUMERIC,
    membrane_dp NUMERIC,
    flow_rate_l_min NUMERIC,
    tank_level NUMERIC,
    tank_status TEXT,
    voltage NUMERIC,
    current NUMERIC,
    power NUMERIC,
    energy_today NUMERIC,
    system_status TEXT DEFAULT 'RUNNING'
);

-- 2. Create alerts table
CREATE TABLE IF NOT EXISTS public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    message TEXT NOT NULL,
    severity TEXT DEFAULT 'Notice',
    status TEXT DEFAULT 'Active'
);

-- 3. Enable Row Level Security (RLS) and allow public read/write for demo/sensor simulator
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on sensor_readings"
    ON public.sensor_readings FOR SELECT
    USING (true);

CREATE POLICY "Allow public insert on sensor_readings"
    ON public.sensor_readings FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow public read access on alerts"
    ON public.alerts FOR SELECT
    USING (true);

CREATE POLICY "Allow public insert on alerts"
    ON public.alerts FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow public delete on alerts"
    ON public.alerts FOR DELETE
    USING (true);

-- 4. Enable Supabase Realtime Replication for instant dashboard live updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_readings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.alerts;
